// <auto-generated />
using System;
using CorpMindAI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CorpMindAI.Infrastructure.Migrations
{
    [DbContext(typeof(CorpMindDbContext))]
    [Migration("20260919024017_AddEmbeddingIndexOutbox")]
    partial class AddEmbeddingIndexOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.AiKnowledgeConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConflictDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conflict_description");

                    b.Property<int>("ConflictingDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("conflicting_document_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedById")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_by");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("source_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConflictingDocumentId");

                    b.HasIndex("ResolvedById");

                    b.HasIndex("SourceDocumentId");

                    b.ToTable("ai_knowledge_conflicts");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric(10, 6)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_used");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChildChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("ChunkingRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("chunking_run_id");

                    b.Property<string>("ComponentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("component_ids");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContextualizedContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contextualized_content");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsAtomic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_atomic");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int>("PageFrom")
                        .HasColumnType("integer")
                        .HasColumnName("page_from");

                    b.Property<int>("PageTo")
                        .HasColumnType("integer")
                        .HasColumnName("page_to");

                    b.Property<string>("ParentChunkId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("parent_chunk_id");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("section_path");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("ChunkingRunId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentChunkId");

                    b.HasIndex("ChunkingRunId", "DocumentId");

                    b.HasIndex("ParentChunkId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("ParentChunkId", "ChunkingRunId", "DocumentId");

                    b.ToTable("child_chunks");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChunkingRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("ChunkerVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chunker_version");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizationNoticesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalization_notices_json");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_content_hash");

                    b.Property<double?>("SourceCoverage")
                        .HasColumnType("double precision")
                        .HasColumnName("source_coverage");

                    b.Property<string>("SourceSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_schema_version");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationWarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasFilter("\"is_active\" = TRUE");

                    b.ToTable("chunking_runs");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.ToTable("curriculums");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("integer")
                        .HasColumnName("curriculum_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("FilePath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsOcrRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ocr_required");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ocr_status");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("RawTextPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("raw_text_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UploadedById");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.OcrResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("components_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("OverallLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_level");

                    b.Property<double>("PageAverageConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("page_average_confidence");

                    b.Property<string>("RawTextPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("raw_text_path");

                    b.Property<DateTime?>("ReconstructedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reconstructed_at");

                    b.Property<string>("ReconstructedStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reconstructed_storage_key");

                    b.Property<string>("ReconstructionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reconstruction_status");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StructuredDocumentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_document_json");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationErrorsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_errors_json");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("ocr_results");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ParentChunk", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("ChunkingRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("chunking_run_id");

                    b.Property<string>("ComponentIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("component_ids");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsAtomic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_atomic");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int>("PageFrom")
                        .HasColumnType("integer")
                        .HasColumnName("page_from");

                    b.Property<int>("PageTo")
                        .HasColumnType("integer")
                        .HasColumnName("page_to");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("section_path");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("ChunkingRunId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ChunkingRunId", "DocumentId");

                    b.HasIndex("ChunkingRunId", "Ordinal")
                        .IsUnique();

                    b.ToTable("parent_chunks");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.HasKey("UserId", "RoleId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("CorpMindAI.Infrastructure.Data.Entities.ChunkingOutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hangfire_job_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("OcrPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ocr_payload_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt", "NextAttemptAt");

                    b.HasIndex("DocumentId", "OcrPayloadHash")
                        .IsUnique();

                    b.ToTable("chunking_outbox_messages");
                });

            modelBuilder.Entity("CorpMindAI.Infrastructure.Data.Entities.EmbeddingIndexOutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ChunkingRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("chunking_run_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hangfire_job_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkingRunId")
                        .IsUnique();

                    b.HasIndex("CompletedAt", "DispatchedAt", "NextAttemptAt");

                    b.ToTable("embedding_index_outbox_messages");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.AiKnowledgeConflict", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Document", "ConflictingDocument")
                        .WithMany("ConflictingConflicts")
                        .HasForeignKey("ConflictingDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpMindAI.Domain.Entities.User", "ResolvedBy")
                        .WithMany("ResolvedConflicts")
                        .HasForeignKey("ResolvedById");

                    b.HasOne("CorpMindAI.Domain.Entities.Document", "SourceDocument")
                        .WithMany("SourceConflicts")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConflictingDocument");

                    b.Navigation("ResolvedBy");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChildChunk", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.ChunkingRun", "ChunkingRun")
                        .WithMany()
                        .HasForeignKey("ChunkingRunId", "DocumentId")
                        .HasPrincipalKey("Id", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpMindAI.Domain.Entities.ParentChunk", "ParentChunk")
                        .WithMany("ChildChunks")
                        .HasForeignKey("ParentChunkId", "ChunkingRunId", "DocumentId")
                        .HasPrincipalKey("Id", "ChunkingRunId", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkingRun");

                    b.Navigation("ParentChunk");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChunkingRun", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Document", "Document")
                        .WithMany("ChunkingRuns")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Curriculum", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedCurriculums")
                        .HasForeignKey("CreatedById");

                    b.HasOne("CorpMindAI.Domain.Entities.Department", "Department")
                        .WithMany("Curriculums")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Document", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.User", "ApprovedBy")
                        .WithMany("ApprovedDocuments")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CorpMindAI.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("Documents")
                        .HasForeignKey("CurriculumId");

                    b.HasOne("CorpMindAI.Domain.Entities.Department", "Department")
                        .WithMany("Documents")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpMindAI.Domain.Entities.User", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");

                    b.Navigation("Curriculum");

                    b.Navigation("Department");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.OcrResult", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Document", "Document")
                        .WithOne("OcrResult")
                        .HasForeignKey("CorpMindAI.Domain.Entities.OcrResult", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ParentChunk", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.ChunkingRun", "ChunkingRun")
                        .WithMany("ParentChunks")
                        .HasForeignKey("ChunkingRunId", "DocumentId")
                        .HasPrincipalKey("Id", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkingRun");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.User", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Department", "Department")
                        .WithMany("UserRoles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpMindAI.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorpMindAI.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CorpMindAI.Infrastructure.Data.Entities.ChunkingOutboxMessage", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CorpMindAI.Infrastructure.Data.Entities.EmbeddingIndexOutboxMessage", b =>
                {
                    b.HasOne("CorpMindAI.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ChunkingRun", b =>
                {
                    b.Navigation("ParentChunks");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Department", b =>
                {
                    b.Navigation("Curriculums");

                    b.Navigation("Documents");

                    b.Navigation("UserRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Document", b =>
                {
                    b.Navigation("ChunkingRuns");

                    b.Navigation("ConflictingConflicts");

                    b.Navigation("OcrResult");

                    b.Navigation("SourceConflicts");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.ParentChunk", b =>
                {
                    b.Navigation("ChildChunks");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CorpMindAI.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ApprovedDocuments");

                    b.Navigation("ChatSessions");

                    b.Navigation("CreatedCurriculums");

                    b.Navigation("ResolvedConflicts");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
